#!/usr/bin/env bash

function StartHomeAssistant {
  echo "Copy configuration.yaml"
  cp -f .devcontainer/configuration.yaml /config || echo ".devcontainer/configuration.yaml is missing!" exit 1
  cp -f .devcontainer/ui-lovelace.yaml /config || echo ".devcontainer/ui-lovelace.yaml is missing!" exit 1

  echo "Copy the lovelace plugin"
  rm -R /config/www/* || echo ""
  cp -r dist/. /config/www/ || echo "Could not copy the lovelace plugin" exit 1

  echo "Start Home Assistant"
  hass -c /config
}

function UpdgradeHomeAssistantDev {
  python -m pip install --upgrade git+https://github.com/home-assistant/home-assistant@dev
}

function SetHomeAssistantVersion {
  read -p 'Version: ' version
  python -m pip install --upgrade homeassistant==$version
}

function HomeAssistantConfigCheck {
  hass -c /config --script check_config
}